### ISSUE TITLE
missing setup step

### ISSUE THREAD

**Issue by m3o7** [atheriel/accessibility#1]
Hi,

great library! I ran into a small issue with the setup when I tried to generate the documentation. Before I could run `step 3` successfully I had to run:

``` bash
# being in <repo>/docs
cd theme
git submodule update --init --recursive
```

Only then I was able to run `make html`, since the theme was not there and I received the build error:

```
Theme error:
no theme named 'theme' found (missing theme.conf?)
make: *** [html] Error 1
```

So, you might want to add this to the setup steps.

Best,
Marco

**Comment by atheriel** [comment]
Thanks for the heads-up! I've fixed the commands in the README. I'm glad you find the library useful.
